name: doitlive
base: core18
version: git
summary: Because sometimes you need to do it live
description: |
  doitlive is a tool for live presentations in the terminal. It reads a file
  of shell commands and replays the commands in a fake terminal session as you
  type random characters.

grade: stable
confinement: classic

parts:
  doitlive:
    plugin: python
    source: .

apps:
  doitlive:
    command: usr/bin/python3 $SNAP/bin/doitlive

